/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/": {
    get: {
      responses: {
        /** OK */
        200: unknown;
      };
    };
  };
  "/Subject": {
    get: {
      parameters: {
        query: {
          id?: parameters["rowFilter.Subject.id"];
          created_at?: parameters["rowFilter.Subject.created_at"];
          name?: parameters["rowFilter.Subject.name"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["Subject"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** Subject */
          Subject?: definitions["Subject"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          id?: parameters["rowFilter.Subject.id"];
          created_at?: parameters["rowFilter.Subject.created_at"];
          name?: parameters["rowFilter.Subject.name"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          id?: parameters["rowFilter.Subject.id"];
          created_at?: parameters["rowFilter.Subject.created_at"];
          name?: parameters["rowFilter.Subject.name"];
        };
        body: {
          /** Subject */
          Subject?: definitions["Subject"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
  "/Job": {
    get: {
      parameters: {
        query: {
          id?: parameters["rowFilter.Job.id"];
          created_at?: parameters["rowFilter.Job.created_at"];
          name?: parameters["rowFilter.Job.name"];
          description?: parameters["rowFilter.Job.description"];
          subjectIDs?: parameters["rowFilter.Job.subjectIDs"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["Job"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** Job */
          Job?: definitions["Job"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          id?: parameters["rowFilter.Job.id"];
          created_at?: parameters["rowFilter.Job.created_at"];
          name?: parameters["rowFilter.Job.name"];
          description?: parameters["rowFilter.Job.description"];
          subjectIDs?: parameters["rowFilter.Job.subjectIDs"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          id?: parameters["rowFilter.Job.id"];
          created_at?: parameters["rowFilter.Job.created_at"];
          name?: parameters["rowFilter.Job.name"];
          description?: parameters["rowFilter.Job.description"];
          subjectIDs?: parameters["rowFilter.Job.subjectIDs"];
        };
        body: {
          /** Job */
          Job?: definitions["Job"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
}

export interface definitions {
  Subject: {
    /**
     * Format: bigint
     * @description Note:
     * This is a Primary Key.<pk/>
     */
    id: number;
    /**
     * Format: timestamp with time zone
     * @default now()
     */
    created_at?: string;
    /** Format: text */
    name: string;
  };
  Job: {
    /**
     * Format: bigint
     * @description Note:
     * This is a Primary Key.<pk/>
     */
    id: number;
    /**
     * Format: timestamp with time zone
     * @default now()
     */
    created_at?: string;
    /** Format: text */
    name: string;
    /** Format: text */
    description?: string;
    /** Format: ARRAY */
    subjectIDs: unknown[];
  };
}

export interface parameters {
  /**
   * @description Preference
   * @enum {string}
   */
  preferParams: "params=single-object";
  /**
   * @description Preference
   * @enum {string}
   */
  preferReturn: "return=representation" | "return=minimal" | "return=none";
  /**
   * @description Preference
   * @enum {string}
   */
  preferCount: "count=none";
  /** @description Filtering Columns */
  select: string;
  /** @description On Conflict */
  on_conflict: string;
  /** @description Ordering */
  order: string;
  /** @description Limiting and Pagination */
  range: string;
  /**
   * @description Limiting and Pagination
   * @default items
   */
  rangeUnit: string;
  /** @description Limiting and Pagination */
  offset: string;
  /** @description Limiting and Pagination */
  limit: string;
  /** @description Subject */
  "body.Subject": definitions["Subject"];
  /** Format: bigint */
  "rowFilter.Subject.id": string;
  /** Format: timestamp with time zone */
  "rowFilter.Subject.created_at": string;
  /** Format: text */
  "rowFilter.Subject.name": string;
  /** @description Job */
  "body.Job": definitions["Job"];
  /** Format: bigint */
  "rowFilter.Job.id": string;
  /** Format: timestamp with time zone */
  "rowFilter.Job.created_at": string;
  /** Format: text */
  "rowFilter.Job.name": string;
  /** Format: text */
  "rowFilter.Job.description": string;
  /** Format: ARRAY */
  "rowFilter.Job.subjectIDs": string;
}

export interface operations {}

export interface external {}
